### ISSUE TITLE
Reduce Channel Noise Improvement Proposal

### ISSUE THREAD

**Issue by brainrepo** [nearform/github-board-slack-notifications#587]
# Problem 
The *technology-hub-board-notifications* channel tends to be noisy.
The causes are 

1. The link preview tends to give lots of not needed information.
2. For each dependabot action (ex. state change), a new message is sent

![image](https://user-images.githubusercontent.com/1851362/233334798-47a00504-d133-4661-b593-b9cb0f4870ed.png)

# Solution proposal

1. As I saw, slack allows us to fold the link preview using this feature https://api.slack.com/reference/messaging/link-unfurling#no_unfurling_please avoiding the link furling can help the channel to be more concise.
2. We can introduce a better workflow to reduce sending multiple consequent messages for the same issue: When we receive an update for an issue, we can send a Slack message and track the message ID (`ts` prop) in a timed cache with a default TTL (ex. 30min is enough to run all the CI steps). Before sending a new update, we must check if the timed cache contains an element with the same id, if yes update the message with the last status (https://api.slack.com/methods/chat.update), and reply to it (https://api.slack.com/messaging/sending#threading) inserting the last status to keep track of all events occurred in the pr.

I know that this means we need to have data storage for that. Since we are on AWS, I suggest using Dynamo DB. It scales to 0, is cheap for our use case and data load, and supports TTLs (https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/TTL.html).

**Comment by simoneb** [comment]
Thanks Mauro:

1. is this something we can do when sending the message do you think? If so, then we should definitely do it!
2. I think we could really just ignore all dependabot PRs instead

**Comment by brainrepo** [comment]
> Thanks Mauro:
> 
> 1. Is this something we can do when sending the message do you think? If so, then we should definitely do it!
> 2. I think we could really just ignore all dependabot PRs instead

I think we can, according to the docs if we have the `links:write` scope, we can just pass the unfurl_links param.
```js
{
    "text": "Check out the <https://api.slack.com|Slack API>",
    "unfurl_links": false,
}
```

I havent tried it, but I think it should work.

**Comment by andrejstas** [comment]
I used `unfurl_links` before and it worked well - previews were removed 👍

**Comment by simoneb** [comment]
Ok cool, let's settle on this then 👌

**Comment by simoneb** [comment]
@brainrepo this is not done yet. We need to filter out dependabot PRs!
